/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UUID = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CourseModule = IDL.Record({
  'moduleId' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'slides' : IDL.Vec(IDL.Text),
  'courseId' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'courseModules' : IDL.Vec(CourseModule),
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'durationWeeks' : IDL.Nat,
});
export const Time = IDL.Int;
export const Certificate = IDL.Record({
  'studentName' : IDL.Text,
  'userId' : IDL.Principal,
  'certificateId' : IDL.Text,
  'issuedAt' : Time,
  'courseId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const User = IDL.Record({
  'id' : IDL.Principal,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'email' : IDL.Text,
  'courseTrack' : IDL.Text,
  'profilePic' : IDL.Opt(ExternalBlob),
});
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : MessageRole,
  'timestamp' : Time,
});
export const ChatSession = IDL.Record({
  'title' : IDL.Text,
  'messages' : IDL.Vec(ChatMessage),
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'sessionId' : UUID,
});
export const Comment = IDL.Record({
  'id' : UUID,
  'content' : IDL.Text,
  'authorId' : IDL.Principal,
  'timestamp' : Time,
  'postId' : UUID,
});
export const FriendRequest = IDL.Record({
  'id' : UUID,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  }),
  'receiverId' : IDL.Principal,
  'senderId' : IDL.Principal,
});
export const Message = IDL.Record({
  'id' : UUID,
  'content' : IDL.Text,
  'receiverId' : IDL.Principal,
  'timestamp' : Time,
  'senderId' : IDL.Principal,
});
export const Notification = IDL.Record({
  'id' : UUID,
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'read' : IDL.Bool,
  'timestamp' : Time,
});
export const Post = IDL.Record({
  'id' : UUID,
  'content' : IDL.Text,
  'authorId' : IDL.Principal,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([UUID, IDL.Text], [], []),
  'adminIssueCertificate' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'createPost' : IDL.Func([IDL.Text], [], []),
  'deleteChatSession' : IDL.Func([UUID], [], []),
  'getAIDevelopmentCourse' : IDL.Func([], [Course], ['query']),
  'getAIDevelopmentModules' : IDL.Func([], [IDL.Vec(CourseModule)], ['query']),
  'getAllCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCertificatesForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Certificate)],
      ['query'],
    ),
  'getChatSession' : IDL.Func([UUID], [ChatSession], ['query']),
  'getCommentsForPost' : IDL.Func([UUID], [IDL.Vec(Comment)], ['query']),
  'getEnrollmentStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'aiDev' : IDL.Nat,
          'gameDev' : IDL.Nat,
          'dappDev' : IDL.Nat,
          'mobileDev' : IDL.Nat,
          'webDev' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getFriendRequestsForUser' : IDL.Func(
      [],
      [IDL.Vec(FriendRequest)],
      ['query'],
    ),
  'getMessagesWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getNotificationsForUser' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPostsForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getSavedChatsForCurrentUser' : IDL.Func(
      [],
      [IDL.Vec(ChatSession)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [User], ['query']),
  'initializeAIDevelopmentCourse' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'issueCertificate' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'likePost' : IDL.Func([UUID], [], []),
  'markNotificationAsRead' : IDL.Func([UUID], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'respondToFriendRequest' : IDL.Func([UUID, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([User], [], []),
  'saveChatSession' : IDL.Func([IDL.Text, IDL.Vec(ChatMessage)], [UUID], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateProfilePic' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UUID = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CourseModule = IDL.Record({
    'moduleId' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'slides' : IDL.Vec(IDL.Text),
    'courseId' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'courseModules' : IDL.Vec(CourseModule),
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'durationWeeks' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Certificate = IDL.Record({
    'studentName' : IDL.Text,
    'userId' : IDL.Principal,
    'certificateId' : IDL.Text,
    'issuedAt' : Time,
    'courseId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const User = IDL.Record({
    'id' : IDL.Principal,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'email' : IDL.Text,
    'courseTrack' : IDL.Text,
    'profilePic' : IDL.Opt(ExternalBlob),
  });
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : MessageRole,
    'timestamp' : Time,
  });
  const ChatSession = IDL.Record({
    'title' : IDL.Text,
    'messages' : IDL.Vec(ChatMessage),
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'lastUpdated' : Time,
    'sessionId' : UUID,
  });
  const Comment = IDL.Record({
    'id' : UUID,
    'content' : IDL.Text,
    'authorId' : IDL.Principal,
    'timestamp' : Time,
    'postId' : UUID,
  });
  const FriendRequest = IDL.Record({
    'id' : UUID,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
      'accepted' : IDL.Null,
    }),
    'receiverId' : IDL.Principal,
    'senderId' : IDL.Principal,
  });
  const Message = IDL.Record({
    'id' : UUID,
    'content' : IDL.Text,
    'receiverId' : IDL.Principal,
    'timestamp' : Time,
    'senderId' : IDL.Principal,
  });
  const Notification = IDL.Record({
    'id' : UUID,
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'read' : IDL.Bool,
    'timestamp' : Time,
  });
  const Post = IDL.Record({
    'id' : UUID,
    'content' : IDL.Text,
    'authorId' : IDL.Principal,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([UUID, IDL.Text], [], []),
    'adminIssueCertificate' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'createPost' : IDL.Func([IDL.Text], [], []),
    'deleteChatSession' : IDL.Func([UUID], [], []),
    'getAIDevelopmentCourse' : IDL.Func([], [Course], ['query']),
    'getAIDevelopmentModules' : IDL.Func(
        [],
        [IDL.Vec(CourseModule)],
        ['query'],
      ),
    'getAllCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCertificatesForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Certificate)],
        ['query'],
      ),
    'getChatSession' : IDL.Func([UUID], [ChatSession], ['query']),
    'getCommentsForPost' : IDL.Func([UUID], [IDL.Vec(Comment)], ['query']),
    'getEnrollmentStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'aiDev' : IDL.Nat,
            'gameDev' : IDL.Nat,
            'dappDev' : IDL.Nat,
            'mobileDev' : IDL.Nat,
            'webDev' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getFriendRequestsForUser' : IDL.Func(
        [],
        [IDL.Vec(FriendRequest)],
        ['query'],
      ),
    'getMessagesWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getNotificationsForUser' : IDL.Func(
        [],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPostsForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getSavedChatsForCurrentUser' : IDL.Func(
        [],
        [IDL.Vec(ChatSession)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [User], ['query']),
    'initializeAIDevelopmentCourse' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'issueCertificate' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'likePost' : IDL.Func([UUID], [], []),
    'markNotificationAsRead' : IDL.Func([UUID], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'respondToFriendRequest' : IDL.Func([UUID, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([User], [], []),
    'saveChatSession' : IDL.Func([IDL.Text, IDL.Vec(ChatMessage)], [UUID], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateProfilePic' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };