/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certificate {
  'studentName' : string,
  'userId' : Principal,
  'certificateId' : string,
  'issuedAt' : Time,
  'courseId' : string,
}
export interface ChatMessage {
  'content' : string,
  'role' : MessageRole,
  'timestamp' : Time,
}
export interface ChatSession {
  'title' : string,
  'messages' : Array<ChatMessage>,
  'userId' : Principal,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'sessionId' : UUID,
}
export interface Comment {
  'id' : UUID,
  'content' : string,
  'authorId' : Principal,
  'timestamp' : Time,
  'postId' : UUID,
}
export interface Course {
  'id' : string,
  'title' : string,
  'courseModules' : Array<CourseModule>,
  'difficulty' : string,
  'description' : string,
  'durationWeeks' : bigint,
}
export interface CourseModule {
  'moduleId' : string,
  'title' : string,
  'description' : string,
  'slides' : Array<string>,
  'courseId' : string,
}
export type ExternalBlob = Uint8Array;
export interface FriendRequest {
  'id' : UUID,
  'status' : { 'pending' : null } |
    { 'rejected' : null } |
    { 'accepted' : null },
  'receiverId' : Principal,
  'senderId' : Principal,
}
export interface Message {
  'id' : UUID,
  'content' : string,
  'receiverId' : Principal,
  'timestamp' : Time,
  'senderId' : Principal,
}
export type MessageRole = { 'user' : null } |
  { 'assistant' : null };
export interface Notification {
  'id' : UUID,
  'content' : string,
  'userId' : Principal,
  'read' : boolean,
  'timestamp' : Time,
}
export interface Post {
  'id' : UUID,
  'content' : string,
  'authorId' : Principal,
  'timestamp' : Time,
}
export type Time = bigint;
export type UUID = string;
export interface User {
  'id' : Principal,
  'username' : string,
  'displayName' : string,
  'email' : string,
  'courseTrack' : string,
  'profilePic' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[UUID, string], undefined>,
  'adminIssueCertificate' : ActorMethod<[Principal, string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNotification' : ActorMethod<[Principal, string], undefined>,
  'createPost' : ActorMethod<[string], undefined>,
  'deleteChatSession' : ActorMethod<[UUID], undefined>,
  'getAIDevelopmentCourse' : ActorMethod<[], Course>,
  'getAIDevelopmentModules' : ActorMethod<[], Array<CourseModule>>,
  'getAllCertificates' : ActorMethod<[], Array<Certificate>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [User]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCertificatesForUser' : ActorMethod<[Principal], Array<Certificate>>,
  'getChatSession' : ActorMethod<[UUID], ChatSession>,
  'getCommentsForPost' : ActorMethod<[UUID], Array<Comment>>,
  'getEnrollmentStats' : ActorMethod<
    [],
    {
      'aiDev' : bigint,
      'gameDev' : bigint,
      'dappDev' : bigint,
      'mobileDev' : bigint,
      'webDev' : bigint,
    }
  >,
  'getFriendRequestsForUser' : ActorMethod<[], Array<FriendRequest>>,
  'getMessagesWithUser' : ActorMethod<[Principal], Array<Message>>,
  'getNotificationsForUser' : ActorMethod<[], Array<Notification>>,
  'getPostsForUser' : ActorMethod<[Principal], Array<Post>>,
  'getSavedChatsForCurrentUser' : ActorMethod<[], Array<ChatSession>>,
  'getUserProfile' : ActorMethod<[Principal], User>,
  'initializeAIDevelopmentCourse' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'issueCertificate' : ActorMethod<[Principal, string, string], string>,
  'likePost' : ActorMethod<[UUID], undefined>,
  'markNotificationAsRead' : ActorMethod<[UUID], undefined>,
  'registerUser' : ActorMethod<[string, string, string, string], undefined>,
  'respondToFriendRequest' : ActorMethod<[UUID, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[User], undefined>,
  'saveChatSession' : ActorMethod<[string, Array<ChatMessage>], UUID>,
  'sendFriendRequest' : ActorMethod<[Principal], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'updateProfilePic' : ActorMethod<[[] | [ExternalBlob]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];